config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :boats do
    resources :bookings, only: %i[create]
  end

  resources :bookings, only: %i[show destroy] do
    get 'confirm', to: :confirm
    get 'accept', to: :accept
  end

  resources :dashboard, only: %i[index]

  get 'dashboard/my_bookings', to: 'dashboard#my_bookings'
  get 'dashboard/my_boats', to: 'dashboard#my_boats'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :user
  has_many :bookings
  # has_one_attached :photo
  has_many_attached :photos

  validates :name, :make_model_year, :location, :price_per_day, :description, :capacity, presence: true
  validates :price_per_day, :capacity, numericality: true
  # validates :type, inclusion: { in: %w[small medium big huge] }

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :boat

  validates :date_end, :date_start, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :boats
  has_one_attached :photo

  validates :first_name, :last_name, :phone_number, :email, :password, :date_of_birth, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :current_password, :photo) }
  end
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  def index
    @boats = Boat.all
    @markers = @boats.geocoded.map do |boat|
      {
        lat: boat.latitude,
        lng: boat.longitude,
        info_window: render_to_string(
          partial: "info_window",
          locals: { boat: boat }
        ),
        image_url: helpers.asset_url("redboat.png")
      }
    end
  end

  def show
    @boat = Boat.find(params[:id])
    @booking = Booking.new
    @user = @boat.user
  end

  def edit
    @boat = Boat.find(params[:id])
  end

  def update
    @boat = Boat.find(params[:id])
    @boat.update(boat_params)

    redirect_to dashboard_my_boats_path
  end

  def create
    @boat = Boat.new(boat_params)
    @boat.user = current_user
    if @boat.save
      redirect_to dashboard_my_boats_path
    else
      render :new
    end
  end

  def new
    @boat = Boat.new
  end

  def destroy
    @boat = Boat.find(params[:id])
    @boat.destroy
    redirect_to dashboard_my_boats_path
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :make_model_year, :location, :price_per_day, :capacity, :description, photos: [])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @boat = Boat.find(params[:boat_id])
    @booking.boat = @boat
    if @booking.save
      redirect_to booking_confirm_path(@booking)
    else
      render :show
    end
  end

  def new
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_my_bookings_path
  end

  def confirm
    @booking = Booking.find(params[:booking_id])
  end

  def accept
    @booking = Booking.find(params[:booking_id])
    @booking.update(confirmed: true)
    redirect_to dashboard_my_bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:date_start, :date_end)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user = current_user
    @bookings_count = Booking.where(user: current_user).count
    if current_user.owner
      @booking_requests_count = Booking.where(boat: current_user.boats).count
      @boats_count = Boat.where(user: current_user).count
    end
  end

  def my_bookings
    @bookings = Booking.where(user: current_user)
    @booking_requests = Booking.where(boat: current_user.boats)
  end

  def my_boats
    @boats = Boat.where(user: current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boats/_info_window.html.erb
<h2><%= link_to boat.name, boat_path(boat), class:"mapboxgl-popup-content" %></h2>
<p><%= boat.location %></p>

app/views/boats/create.html.erb
<h1>Boats#create</h1>
<p>Find me in app/views/boats/create.html.erb</p>

app/views/boats/edit.html.erb
<div class="wrapper m-3">
  <div class="container">
    <h1>Edit Boat</h1>
    <%= simple_form_for(@boat) do |f| %>
      <%= f.input :name %>
      <%= f.input :make_model_year %>
      <%= f.input :location %>
      <%= f.input :price_per_day %>
      <%= f.input :capacity %>
      <%= f.input :description %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.submit 'Confirm Edits' %>
    <% end %>
  </div>
</div>

app/views/boats/index.html.erb
<div class="row">
  <div class="col-8">
    <div class="row row-cols-3 m-3">
      <% @boats.each do |boat| %>
        <div class="col">
          <div class="card mb-3 mt-3" style="max-width: 540px;">
            <%= link_to boat_path(boat) do %>
              <% if boat.photos.count > 0 %>
                <% first = boat.photos.first %>
                <% photo_url = cl_image_path(first.key) %>
                <img src="<%= photo_url %>" class="card-img-top" style="height: 200px; object-fit: cover;" alt="A beautiful large boat">
              <% else %>
                <img src="https://electrek.co/wp-content/uploads/sites/3/2021/09/duck-boat-header.jpg" class="card-img-top" style="height: 200px; object-fit: cover;" alt="boat parked">
              <% end %>
            <% end %>
            <div class="card-body" >
              <h5 class="card-title"><%= boat.name %></h5>
              <% if boat.description.length > 60 %>
                <p class="card-text"><%= boat.description[0,50] %>...</p>
              <% else %>
                <p class="card-text"><%= boat.description%></p>
              <% end %>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Location: <%= boat.location %></li>
              <li class="list-group-item">Capacity: <%= boat.capacity %> people</li>
              <li class="list-group-item">Price: $<%= boat.price_per_day.to_s(:delimited) %>/day</li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-4">
    <div class="sticky-top" style="z-index: 80;">
      <div style="width: 100%; height: 100vh;"
        data-controller="mapbox"
        data-mapbox-markers-value="<%= @markers.to_json %>"
        data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/boats/new.html.erb
<div class="wrapper m-3">
  <div class="container">
    <h1>New Boat</h1>
    <%= simple_form_for(@boat) do |f| %>
      <%= f.input :name %>
      <%= f.input :make_model_year %>
      <%= f.input :location %>
      <%= f.input :price_per_day %>
      <%= f.input :capacity %>
      <%= f.input :description %>
      <%#= f.input :photo, as: :file %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.submit 'Add boat' %>
    <% end %>
  </div>
</div>

app/views/boats/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1><%= @boat.name %></h1>
      <p><%= @boat.location %></p>
    </div>
    <div class="col-8">

     <div id="boatImagesCarousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <% @boat.photos.each_with_index do |photo, index| %>
            <% if index == 0 %>
              <button type="button" data-bs-target="#boatImagesCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <% else %>
              <button type="button" data-bs-target="#boatImagesCarousel" data-bs-slide-to="<%= index %>" aria-label="Slide <%= index + 1 %> "></button>
            <% end %>
          <% end %>
        </div>

        <div class="carousel-inner">
           <% @boat.photos.each_with_index do |photo, index| %>
            <% if index == 0 %>
                <div class="carousel-item active">
                  <% photo_url = cl_image_path(photo.key) %>
                  <img src="<%= photo_url %>"  class="d-block w-100" style="max-height: 600px; object-fit: cover;" alt="A different angle of the same boat">
                </div>
            <% else %>
                <div class="carousel-item">
                  <% photo_url = cl_image_path(photo.key) %>
                  <img src="<%= photo_url %>"  class="d-block w-100" style="max-height: 600px; object-fit: cover;" alt="A different angle of the same boat">
                </div>
            <% end %>
          <% end %>
        </div>

        <button class="carousel-control-prev" type="button" data-bs-target="#boatImagesCarousel" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#boatImagesCarousel" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>

      </div>

      <ul class="list-group list-group-flush">
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Description: </div>
            <%= @boat.description %>
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Location: </div>
            <%= @boat.location %>
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Capacity: </div>
            <%= @boat.capacity %>
          </div>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold">Price: </div>
            $<%= @boat.price_per_day.to_s(:delimited) %>/day
          </div>
        </li>
      </ul>
    </div>

    <div class="col-4">
    <div class="card" style="width: 20rem;">
      <div class="card-body">
        <div class="d-flex justify-content-between">
          <div>
            <h5 class="card-title">$<%= @boat.price_per_day.to_s(:delimited) %>/day</h5>
            <h6 class="card-subtitle mb-2 text-muted">Provided by <%= @boat.user.first_name %></h6>
          </div>
          <div>
            <% photo_url = @user.photo.key.nil? ? 'https://cdn.iconscout.com/icon/free/png-256/avatar-370-456322.png' : cl_image_path(@user.photo.key) %>
            <%= image_tag photo_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          </div>
        </div>

          <%= simple_form_for([@boat, @booking]) do |f| %>
            <%= f.input :date_start %>
            <%= f.input :date_end %>
            <%= f.submit 'Book Now', data: { confirm: "Ready to confirm this booking?" }, class:'btn btn-success w-100'%>
          <% end %>

          <%= link_to "Contact #{@boat.user.first_name}", '#', data: { confirm: "You can contact #{@boat.user.first_name} at #{@boat.user.phone_number}" }, class:"btn btn-secondary w-100 mt-2"%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/boats/update.html.erb
<h1>Boats#update</h1>
<p>Find me in app/views/boats/update.html.erb</p>

app/views/bookings/confirm.html.erb
<div class="container mt-3">
  <div class="text-center">
    <h1>Booking Confirmed</h1>
    <p>Thank you for using WaterBnB as your boat rental service!</p>
  </div>
  <div class="row row-cols-1 row-cols-md-2 g-4">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="card text-white bg-success mt-3 mb-3">
        <h5 class="card-header text-center">Booking for <%= @booking.boat.name %> was successful!</h5>
        <div class="card-body">
          <h5 class="card-title">Request has been sent to <%= @booking.boat.user.first_name %></h5>
          <p class="card-text">Booking details:</p>
          <ul class="list-group list-group-flush bg-transparent">
            <li class="list-group-item d-flex justify-content-between align-items-center">
              From:
              <span><%= @booking.date_start %></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Until:
              <span><%= @booking.date_end %></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Total:
              <span><%= (@booking.date_end - @booking.date_start).to_i %> days</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Total Cost:
              <span><% total = (@booking.date_end - @booking.date_start).to_i * @booking.boat.price_per_day %>
              $<%= total.to_s(:delimited) %>
              </span>
            </li>
          </ul>
        </div>
        <div class="card-footer">
          <div class="row row-cols-1 row-cols-md-2 g-0">
            <div class="col-md-6 text-center">
              <%= link_to 'My Bookings', dashboard_my_bookings_path, class:"btn btn-dark btn-lg" %>
            </div>
            <div class="col-md-6 text-center">
              <%= link_to 'Browse Boats', boats_path, class:"btn btn-dark btn-lg" %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="container mt-3">
  <h1>Dashboard</h1>
  <br>
  <h3>Welcome <%= @user.first_name %></h3>
  <div class="card mt-3 mb-3" style="max-width: 600px;">
    <div class="row g-0">
      <div class="col-md-4">
        <% photo_url = current_user.photo.key.nil? ? 'https://cdn.iconscout.com/icon/free/png-256/avatar-370-456322.png' : cl_image_path(current_user.photo.key) %>
        <img src="<%= photo_url %>" class="img-fluid rounded-start" alt="user profile picture">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <div class="row g-0">
            <div class="col-md-8">
              <h5 class="card-title">My Info</h5>
            </div>
            <div class="col-md-4 text-end">
              <%= link_to 'Edit', edit_user_registration_path, class:"btn btn-outline-danger" %>
            </div>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= @user.first_name %> <%= @user.last_name %></li>
            <li class="list-group-item">Phone: <%= @user.phone_number %></li>
            <li class="list-group-item">Birthdate: <%= @user.date_of_birth %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <br>
  <h3>My Booking</h3>
  <div class="row row-cols-1 row-cols-md-2 g-4">
    <div class="col">
      <div class="card border-info mb-3">
        <div class="card-header">You currently have <%= @bookings_count.to_s %> bookings</div>
        <div class="card-body">
          <h5 class="card-title">
            <% if @bookings_count.zero? %>
              You have no bookings
            <% else %>
              Thank you for booking!
            <% end %>
          </h5>
          <% if @bookings_count.zero? %>
            <p class="card-text">Go browse some boats to book!</p>
            <%= link_to 'Browse Boats', boats_path, class:"btn btn-outline-success" %>
          <% else %>
            <p class="card-text">Check your bookings here.</p>
            <%= link_to 'My Bookings', dashboard_my_bookings_path, class:"btn btn-outline-success" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <br>
  <% if @user.owner %>
    <h3>My Boats</h3>
    <div class="row row-cols-1 row-cols-md-2 g-4">
      <div class="col">
        <div class="card border-info mb-3">
          <div class="card-header">You currently have <%= @boats_count.to_s %> boats</div>
          <div class="card-body">
            <h5 class="card-title">
              <% if @boats_count.zero? %>
                You have no boats!
              <% else %>
                What great boats you have there!
              <% end %>
            </h5>
            <% if @boats_count.zero? %>
              <p class="card-text">As a boat owner its only natural to add your boat on WaterBnB right?</p>
              <%= link_to 'Add Boats', new_boat_path, class:"btn btn-outline-success" %>
            <% else %>
              <p class="card-text">Check your boats here.</p>
              <%= link_to 'My Boats', dashboard_my_boats_path, class:"btn btn-outline-success" %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="card border-info mb-3">
          <div class="card-header">You currently have <%= @booking_requests_count.to_s %> boat requests</div>
          <div class="card-body">
            <h5 class="card-title">
              <% if @booking_requests_count.zero? %>
                No one booked your boat yet
              <% else %>
                You have some booking requests pending!
              <% end %>
            </h5>
            <% if @booking_requests_count.zero? %>
              <p class="card-text">Do you have another boat to add? It will definitely increase your chances of booking!</p>
              <%= link_to 'Add Boats', new_boat_path, class:"btn btn-outline-success" %>
            <% else %>
              <p class="card-text">Check your requests here.</p>
              <%= link_to 'My Bookings', dashboard_my_bookings_path, class:"btn btn-outline-success" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/dashboard/my_boats.html.erb
<div class="container mt-3">
  <div class="row row-cols-2 mb-3">
    <div class="col"><h1>My Boats</h1></div>
    <div class="col text-end"><%= link_to 'Add New Boat', new_boat_path, class:"btn btn-outline-success" %></div>
  </div>
  <div class="row row-cols-1 row-cols-md-4 g-4">
    <% @boats.each do |boat| %>
      <div class="col">
        <div class="card">
          <%= link_to boat_path(boat) do %>
            <% if boat.photos.count > 0 %>
              <% photo_url = cl_image_path(boat.photos.first.key) %>
              <img src="<%= photo_url %>" class="card-img-top" style="height: 200px; object-fit: cover;" alt="boat">
            <% else %>
              <img src="https://electrek.co/wp-content/uploads/sites/3/2021/09/duck-boat-header.jpg" class="card-img-top" alt="boat parked">
            <% end %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= boat.name %></h5>
             <% if boat.description.length > 60 %>
              <p class="card-text"><%= boat.description[0,50] %>...</p>
            <% else %>
              <p class="card-text"><%= boat.description%></p>
            <% end %>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Price: $<%= boat.price_per_day %>/day</li>
          </ul>
          <div class="card-footer">
            <div class="row g-3">
              <div class="d-grid gap-2 col-6 mx-auto">
                <%= link_to 'Edit', edit_boat_path(boat), class:"btn btn-outline-primary" %>
              </div>
              <div class="d-grid gap-2 col-6 mx-auto">
                <%= link_to 'Remove', boat_path(boat), method: :delete, data: { confirm: "Remove boat ?" }, class:"btn btn-outline-danger" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>


</div>

app/views/dashboard/my_bookings.html.erb
<div class="container mt-3">
  <div class="row row-cols-2 mb-3">
    <div class="col"><h2>My Bookings</h2></div>
  </div>
  <div class="row row-cols-1 row-cols-md-2 g-4">
    <% @bookings.each do |booking| %>
      <div class="col">
        <div class="card <%= "border-success" if booking.confirmed %>">
          <div class="card-header">
            <% if booking.confirmed %>
              <%= booking.boat.user.first_name %> approved your request!
            <% else %>
              Your request has been sent to <%= booking.boat.user.first_name %>
            <% end %>
          </div>
          <div class="row g-0">
            <div class="col-md-4">
              <% if booking.boat.photos.count > 0 %>
                <% first = booking.boat.photos.first %>
                <% photo_url = cl_image_path(first.key) %>
                <img src="<%= photo_url %>" class="card-img-top" style="height: 140px; object-fit: cover;" alt="A beautiful large boat">
              <% else %>
                <img src="https://electrek.co/wp-content/uploads/sites/3/2021/09/duck-boat-header.jpg" class="card-img-top" style="height: 140px; object-fit: cover;" alt="boat parked">
              <% end %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">
                  <% if booking.confirmed %>
                    You will be renting <%= booking.boat.name %>
                  <% else %>
                    You want to rent <%= booking.boat.name %>
                  <% end %>
                </h5>
                <p class="card-text d-flex justify-content-between align-items-center">
                  From: <span><%= booking.date_start %><br></span>
                </p>
                <p class="card-text d-flex justify-content-between align-items-center">
                  Till: <span><%= booking.date_end %></span>
                </p>
              </div>
            </div>
          </div>
          <div class="card-footer text-center">
              <% if booking.confirmed %>
                <%= link_to "Contact #{booking.boat.user.first_name}", '#', data: { confirm: "You can contact #{booking.boat.user.first_name} at #{booking.boat.user.phone_number}" }, class:"btn btn-secondary"%>
              <% else %>
                <%= link_to "Cancel Request", booking_path(booking), method: :delete, data: { confirm: "Cancel request?" }, class:"btn btn-danger"%>
              <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% if current_user.owner %>
    <br>
    <div class="row row-cols-2 mb-3">
      <div class="col"><h2>My Booking Requests</h2></div>
    </div>
    <div class="row row-cols-1 row-cols-md-2 g-4">
      <% @booking_requests.each do |request| %>
        <div class="col">
          <div class="card <%= "border-success" if request.confirmed %>">
            <div class="card-header">
              <% if request.confirmed %>
                You confirmed this request from <%= request.user.first_name %>
              <% else %>
                New request from <%= request.user.first_name %>!
              <% end %>
            </div>
            <div class="row g-0">
              <div class="col-md-4">
                <% if request.boat.photos.count > 0 %>
                  <% first = request.boat.photos.first %>
                  <% photo_url = cl_image_path(first.key) %>
                  <img src="<%= photo_url %>" class="card-img-top" style="height: 140px; object-fit: cover;" alt="A beautiful large boat">
                <% else %>
                  <img src="https://electrek.co/wp-content/uploads/sites/3/2021/09/duck-boat-header.jpg" class="card-img-top" style="max-height: 150px; object-fit: cover;" alt="boat parked">
                <% end %>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <% if request.confirmed %>
                    <h5 class="card-title"><%= request.user.first_name %> will be renting <%= request.boat.name %></h5>
                  <% else %>
                    <h5 class="card-title"><%= request.user.first_name %> wants to rent <%= request.boat.name %></h5>
                  <% end %>
                  <p class="card-text d-flex justify-content-between align-items-center">
                    From: <span><%= request.date_start %><br></span>
                  </p>
                  <p class="card-text d-flex justify-content-between align-items-center">
                    Till: <span><%= request.date_end %></span>
                  </p>
                </div>
              </div>
            </div>
            <% if request.confirmed %>
              <div class="card-footer d-flex justify-content-evenly align-items-center">
                <%= link_to "Contact #{request.user.first_name}", '#', data: { confirm: "You can contact #{request.user.first_name} at #{request.user.phone_number}" }, class:"btn btn-outline-secondary"%>
                <%= link_to "Cancel Request", booking_path(request), method: :delete, data: { confirm: "Cancel request?" }, class:"btn btn-outline-danger"%>
              </div>
            <% else %>
              <div class="card-footer d-flex justify-content-evenly align-items-center">
                <%= link_to "Accept", booking_accept_path(request), class:"btn btn-outline-success"%>
                <%= link_to "Decline", booking_path(request), method: :delete, data: { confirm: "Decline request?" }, class:"btn btn-outline-danger"%>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pages/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://1gvfbg13xkltmtbpo3cap551-wpengine.netdna-ssl.com/wp-content/uploads/2018/03/banner.jpg);">
  <div class="container">
    <h1>WaterBnb <strong>brings the ocean</strong> to <strong>you</strong>!</h1>
    <p>Change your perception of the sea.</p>
    <%= link_to "Browse available boats", boats_path, class:"btn btn-outline-light"%>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://png.pngtree.com/png-vector/20190328/ourlarge/pngtree-vector-boat-icon-png-image_875460.jpg", :style => "border-radius: 50%" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% photo_url = current_user.photo.key.nil? ? 'https://cdn.iconscout.com/icon/free/png-256/avatar-370-456322.png' : cl_image_path(current_user.photo.key) %>
            <%= image_tag photo_url, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_index_path, class: "dropdown-item" %>
              <!-- add an if statement for my boats -->
              <%= link_to "My Bookings", dashboard_my_bookings_path, class: "dropdown-item" %>
              <% if current_user.owner %>
                <%= link_to "My Boats", dashboard_my_boats_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>